### ISSUE TITLE
Navigation nach Kategorie ordnen

### ISSUE THREAD

**Issue by xDGeForcexD** [IDragonfire/dzcp#108]
Könnt ihr die Navigation im Adminpanel auch so anordnen in der neuen Version?

http://dzcp-zone.de/downloads/?action=show&id=82#

Das halt alles seinen platz hat?
wär schön wenn dann neu erstellte überschriften auch gleich mit drin stehen sobald man diese erstellt.

quelle: http://www.dzcp.de/forum/?action=showthread&id=15217&page=1#p4

ich würde das empfehlen: http://www.dzcp-addons.eu/tutorials/?action=tutorial&id=5 hat auch Hellbz vorgeschlagen und er ist damit einverstanden das es eingebaut wird

**Comment by hybernate** [comment]
Finde ich eine sehr gute idee. Das kann sehr schnell sehr unübersichtlich werden.
