### ISSUE TITLE
CORE: TinyMCE mobile problems

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#11]
http://www.dzcp-zone.de/forum/?action=showthread&id=1785&hl=handy&page=1

TinyMCE funktioniert nicht unter den meisten mobilen Geräten ...

Mögliche Lösung:

Tiny komplett bei mobile devices deaktivieren ...

**Comment by HellBz** [comment]
Nur vom durchlesen bemerke ich einen Fehler...

Wann ich jetzt was schreibe, was ja soweit gehen sollte.

Es besteht noch ein Problem, wenn ich was eingebe und Enter Drücke übernimmt der die \n nicht als <br>

sondern die bleiben \n und somit nur ein nurlaler Text-Umbruch.

Wenn ich mit überlege einen Mobile-detect zu benutzen,
mach das mehr sinn und mit dem Mobile Detect die re() dann gleich mit Modifiziere.

So dass die re() aus einem \n ein
macht und

nebenher die javascrip.Files ausgeschaltet werden.

**Comment by IDragonfire** [comment]
Alles weitere bitte hier posten:

https://github.com/IDragonfire/dzcp/issues/4

#4
