### ISSUE TITLE
Dropdown Menü unter News und im Admin CP bei den Newskategorien

### ISSUE THREAD

**Issue by Insane1990** [IDragonfire/dzcp#110]
Nach Alphabet ordnen (ORDER BY kategorie ASC)

**Comment by IDragonfire** [comment]
meinst du die dropdown menüs zur auswahl der newskategorien?

**Comment by Insane1990** [comment]
ja genau die im adminmenü sowie unter den news selber
bitte alphabetisch

**Comment by Insane1990** [comment]
würde an eurer stelle ALLE dropdowns wo text drin ist nach alphabet ordnen, dient ja der besseren übersicht

**Comment by IDragonfire** [comment]
Bis jetzt hat es keinen gestört,
ich habe dafür leider keine Zeit :(
Man muss ein wenig Prioritäten setzen ...

**Comment by Insane1990** [comment]
naja wenn ihr das generell aber so machen würdet kommt es natürlich noch besser an ;)
is doch nur inner sql abfrage ne ordnung, nur bei dem unter den news bekomm ichs net hin im admincp wars leichter

**Comment by IDragonfire** [comment]
Umlernen ist aufwendiger als damit zu leben ...
