### ISSUE TITLE
Serverviewer im Navi

### ISSUE THREAD

**Issue by Insane1990** [IDragonfire/dzcp#111]
Zentrieren

**Comment by IDragonfire** [comment]
Serverviwer in der Navi? Bitte Issues ein wenig genauer!!!

**Comment by Insane1990** [comment]
Naja wies da steht
Den Serverviewer unten rechts im Navi (im Template) in dem vorhandenen td-tag dafür zentrieren: align="center"

**Comment by hybernate** [comment]
Also navi ist hier für jeden die Seitennavigation. Ich raff genausowenig was du hier willst!!!!

Wenn hier ein issue aufgemacht wird dann wird auch eine detailierte Fehlerbeschreibung dazu geschrieben.
Ansonsten bitte ich darum das sollche issues in Zukunft gelöscht werden.

**Comment by Insane1990** [comment]
den serverviewer der auf der index.html angezeigt wird (vom template)
den bitte centern ;)
