### ISSUE TITLE
Navi (Events und Artikel)

### ISSUE THREAD

**Issue by Insane1990** [IDragonfire/dzcp#112]
Envent- und Artikelbeschreibungen im Navi zentrieren!

**Comment by IDragonfire** [comment]
Was meinst mit zentrieren? und wo? bitte ein wenig genauer?

**Comment by Insane1990** [comment]
im navi auf der rechten seite.

Musst in der css statt text-align: left auf center stellen
In diesen werten:

Diese werte auf der css entfernen: td.navLastArtikelContent,td.navEventsContent

und dann so einfügen darunter:

td.navLastArtikelContent,td.navEventsContent {
  text-align: center;
  vertical-align: middle;

**Comment by hybernate** [comment]
nein!
das ist standart so. dann sind ja alle tabellen wieder falsch. das bleibt so. Kannst du auf deiner seite dann machen wie du möchtest aber standart bleibt standart.

gemeint ist die anzeige latest articles und next events in der rechten Contentspalte.
