### ISSUE TITLE
Partnerbuttons und Sponsoren (auch Vollansicht dieser)

### ISSUE THREAD

**Issue by Insane1990** [IDragonfire/dzcp#113]
Nach Alphabeth anordnen (name ASC)

**Comment by IDragonfire** [comment]
was meinst mit vollansicht?

**Comment by xDGeForcexD** [comment]
ich denk das er die unterseite sponsors und links meint

**Comment by Insane1990** [comment]
wenn man links im navi sponsors und links anklickt.
für Partner könntet ihr das genauso wie bei sponsors machen
dasses da auch button link und banner gibt ;)

bitte alles alphabetisch ;)

**Comment by hybernate** [comment]
wir fixxen bugs in dzcp und wollen eine bugfreie version raus bringen. Das heisst es werden keine neuerungen gemacht.

**Comment by IDragonfire** [comment]
Deswegen ist das ein "enchancement"
