### ISSUE TITLE
Teamspeak IP ohne Port

### ISSUE THREAD

**Issue by Insane1990** [IDragonfire/dzcp#114]
Man kann keine TS-IP ohne Port dahinter eintragen, bitte fixt das, dass man das Port-Eingabefeld auch leer lassen kann. Weil wenn man nur einen TS laufen hat braucht der keinen Port für TS-3!!

**Comment by hammermaps** [comment]
Dürfte der Code ändern,

```
  if($_GET['do'] == "ts")
  {
    if(empty($_POST['ts_port']))
    {
        switch (((int)$_POST['ts_version'])) 
        {
            case "3": //TS3
                $tsport = 9987;
            break;
            default: //TS2
                $tsport = 8767;
            break;
        }
    }
    else
        $tsport = ((int)$_POST['ts_sport']);

    if(empty($_POST['ts_sport']))
    {
        switch(((int)$_POST['ts_version'])) 
        {
            case "3": //TS3
                $tsqport = 10011;
            break;
            default: //TS2
                $tsqport = 51234;
            break;
        }
    }
    else
        $tsqport = ((int)$_POST['ts_sport']);

    $qry = db("UPDATE ".$db['settings']."
               SET `ts_port`        = '".$tsport."',
                   `ts_sport`       = '".$tsqport."',
                   `ts_width`       = '".((int)$_POST['ts_width'])."',
                   `ts_version`     = '".((int)$_POST['ts_version'])."',
                   `ts_ip`          = '".up($_POST['ts_ip'])."',
                   `ts_customicon`  = '".((int)$_POST['ts_customicon'])."',
                   `ts_showchannel` = '".((int)$_POST['ts_showchannel'])."'
               WHERE id = 1");

    $show = info(_config_server_ts_updated,"?admin=server");

  }
```

Wurde nicht getestet!

**Comment by Insane1990** [comment]
bitte testen

**Comment by IDragonfire** [comment]
Hi Godkiller_NT,
willkommen bei github,
du kannst ohne Probleme den Code ändern ...
einfach oben rechts bei meinem Repo (https://github.com/IDragonfire/dzcp)
FORK drücken ...
Dann hast du dein eigenes Repo wo du Dinge nach belieben ändern kannst.
WICHTIG: Jede Änderung erfordert ein Committext (Kommentar) ... Verlinke dort bitte mit #ISSUEID
das entsprechende Issue ...
Solltest du fertig sein kannst du die Änderungen zum Hauptrepo übertragen (oben Rechts Pull Request drücken)

Gruß

Dragonfire

**Comment by Insane1990** [comment]
Bitte nochmal ausbessern, auch bei angegebenem Port trägt er die Standards ein!
Sollte erkennen obs feld leer oder beschrieben is

**Comment by xDGeForcexD** [comment]
Kann nicht sein er prüft berreits ob es leer ist!
Ist dies überhaupt schon in dzcp eingebaut?

**Comment by Insane1990** [comment]
hatte es selber reingebaut den code ^^
aber naja standardport eintragen tuts auch xD

**Comment by xDGeForcexD** [comment]
Weist du überHaupt wo es hin kommt?

Wenn nicht es kommt in die admin/menu/Server.php hoffe du weißt dann an welchen Platz...
