### ISSUE TITLE
Auslagerung der Action Sides

### ISSUE THREAD

**Issue by hammermaps** [IDragonfire/dzcp#115]
Hi, Jungs.
Seit Ja fleissig dran.
Ihr solltet die Cases in den Index Dateien /user/index.php etc. in eingene Dateien packen. 
Das hat deutliche Performance vorteile.

Nur als Tipp von ehmaligen DZCP Coder zu DZCP Coder^^

**Comment by IDragonfire** [comment]
Würden wir dzcp optimieren wollen,
müsste man es neuschreiben ...

aber danke,
sollte wer Zeit haben geht es jetzt nicht verloren xD

Mir ist nicht ganz einleuchtend, 
warum ein auslagern schneller sein sollte ...
Der Server sollte die user/index.php im Cache haben ...

Je nach Konfiguration wäre dies sogar langsamer, da man von Platte nachlesen müsste ...
Einziger Grund dafür ..
die user/index.php wird kleiner und da php eine Interpretersprache ist,
könnte es Auswirkungen bei der Ausführungszeit haben ...

Müsste man mal testen ;)

**Comment by hammermaps** [comment]
Die PHP Files werden in keinen Cache geladen, die werden immer neu abgerufen wenn einer die Seite aufruft.
Da müsste man dann mit einem Memcache arbeiten und die PHP Files dort einschreiben.
