### ISSUE TITLE
Zusammenfassung der Installer.php und der Update.php

### ISSUE THREAD

**Issue by hammermaps** [IDragonfire/dzcp#116]
Eine Zusammenfassung der _Installer/installer.php und der update zu einer index.php mit Auswahl möglichkeit ob Update oder Installation würde vielen das leben erleichtern.

**Comment by IDragonfire** [comment]
_agree_
Das Ding ist sowieso schrecklich ....

Allerdings muss man auch schauen, wo man Aufwand reinsteckt ...
Ich finde dies unwichtig,
zumal diese Dateien eher seltener geändert werden und es nicht so viele Updates gibt ...

Es funktioniert,
wie ein Großteil von dzcp ...
das reicht xD

**Comment by hammermaps** [comment]
Ich hab von der ehmaligen DZCP 1.5.6 einen Installer der so aufgebaut ist, denn hab ich neu geschrieben.
Ihr müsstet nur einige Funktionen im Installer ändern damit das teil auf der alten DZCP Basis funktioniert.
Adde mich mach in ICQ: 209430031 dann kann ich dir den mal senden.
Wenn du möchtest kannst du dir das per TV auch mal bei mir zuhause ansehen.
