### ISSUE TITLE
Unötige funktionen

### ISSUE THREAD

**Issue by hammermaps** [IDragonfire/dzcp#117]
Die Function:
 function safe(){ return; }
in der inc/secure.php
wird bei mir nicht mehr Verwendet man sollte Prüfen ob diese nicht schon überflüssig ist und entfernt werden kann.

**Comment by IDragonfire** [comment]
In der Tat finde ich jetzt keine Stelle wo diese Funktion verwendet wird ...
Sollte man mal entfernen ^^

DANKE
