### ISSUE TITLE
cms/admin/?admin=profile  BUG

### ISSUE THREAD

**Issue by Insane1990** [IDragonfire/dzcp#119]
cms/admin/?admin=profile

Die buttons im Bereich "Sichtbar" haben keinerlei Funktion!

Es wäre schön wenn man statt alles gleich zu löschen, es auch einfach ausblenden könnte wie beim Navi!

**Comment by hybernate** [comment]
tatsache da sind nur bilder drin. aber in der version 1.5.5.2 auch schon ^^

**Comment by Insane1990** [comment]
ja sollte aber funktion haben!

**Comment by hybernate** [comment]
jetzt hat es funktion ^^
Das wurde wohl mal vergessen.
