### ISSUE TITLE
Bestimme zeichen in DB doppelt codiert!

### ISSUE THREAD

**Issue by Insane1990** [IDragonfire/dzcp#120]
Wenn ich Symbold/Zeichen aus der Zeichentabelle z.B. als Nickname:
Ηдллιвдζ

Dann zeigt er in der Datenbank sowie auf meiner Clanpage nur unlesbares zeug in dieser Form an:

Datenbank-Ansicht:
&amp;#919;&amp;#1076;&amp;#1083;&amp;#1083;&amp;#953;&amp;#1074;&amp;#1076;&amp;#950;

Website-Ansicht:
&#919;&#1076;&#1083;&#1083;&#953;&#1074;&#1076;&#950;

Da liegt ein Fehler im CMS vor, denn hier wurde das Sonderzeichen doppelt codiert.

Das eingegebene Sonderzeichen wurde codiert = &#919;
Nun wurden nochmal die Sonderzeichen im codierten Sonderzeichen codiert (in dem Fall wäre das nur das &).
Hierdurch entsteht dann &amp;#919;

Die werte landen schon falsch in der Datenbank, das Problem lässt sich nicht durch die Umstellung des Charsets oder der Collation beheben.

Hier wird dann wohl ein Eingriff in die Programmierung des CMS notwendig sein.

BITTE FIXEN SO DASS ES IN ALLEN EINGABEFELDERN FUNKTIONIERT
Ein gutes CMS sollte schon UTF-8 Kompatibel sein!

**Comment by IDragonfire** [comment]
danke,
werden wir fixen ..

**Comment by Insane1990** [comment]
Und wie gehts voran mit diesem Fix ?
