### ISSUE TITLE
cms/user/?action=editprofile BUG

### ISSUE THREAD

**Issue by Insane1990** [IDragonfire/dzcp#121]
Der Editieren Button am Ende der Page funktionier nicht wenn einige Eingabefelder ausgefüllt werden!

**Comment by IDragonfire** [comment]
das sollte behoben sein,
speziell wird es die Stadt sein ...

**Comment by Insane1990** [comment]
Betrifft glaube ich nur den Wohnort hab gerade jedes einzeln ausgefüllt.
Prüft aber bitte alle!
Bei Wohnort graut sich der Button nur aus aber er aktualisiert nichts

**Comment by IDragonfire** [comment]
https://github.com/IDragonfire/dzcp/commit/fa315d58aca8a7e8d31c8d4f16596eb60086081c

**Comment by Insane1990** [comment]
Stad hatt 2 Worte: Bad Windsheim

**Comment by IDragonfire** [comment]
hast die neuste Version?

**Comment by Insane1990** [comment]
Ich nutze doch keinen Google API aber Stadt sollte er im Profil trotzdem anzeigen!
Nutze die: mit bcb am ende

**Comment by Insane1990** [comment]
Ist die SQL db auch zum entgültigen Release brauchbar, dass man nur die Files updaten brauch?

**Comment by IDragonfire** [comment]
Finde kein Commit mit "bcb" am Ende ...
Schau mal ob die gepostet Änderung auf deiner Seite auch vorhanden ist ...

Auf der Datenbankseite bleibt alles wie beim alten ...

**Comment by Insane1990** [comment]
k ne hab ins zip geschaut is ne neue drin lad mir die mal eben ; )

**Comment by IDragonfire** [comment]
und?

**Comment by Insane1990** [comment]
wie muss ich meine daten in die config php einfügen?
hast ne pn wie ichs gemacht habe + die fehöermeldung -.-

**Comment by Insane1990** [comment]
man binnich blöd, falsche datei xD

**Comment by Insane1990** [comment]
BUG BESTEHT IMMERNOCH!
ort lässt isch net eintragen!

habe jetz nur die files ausgetauscht, per hand.
ganze page geht, nur das nich ^^

**Comment by IDragonfire** [comment]
das JQuery deines Templates ist nicht auf den neusten Stand ...
die von mir verwendetet Funktion jQuery.isNumeric()
gibt es erst seit jQuery 1.7 ...
das alte dzcp hat ein uraltes jQuery ..

**Comment by hybernate** [comment]
das problem hatte ich jetzt bei meiner letzten anpassung auch. Dort habe ich die neue version genutzt. Problem war das die javascript funktion von dem von mir verbauten javascript geblockt wurde. Ich glaub da sollten wir doch noch mal schauen ob wir irgendwas machen könnten.

**Comment by IDragonfire** [comment]
Google hat eine url deaktiviert ...
Wenn nicht hast du nicht das aktuelle jQuery ...
Bei wem geht es nicht?

**Comment by hybernate** [comment]
na ich hatte bei einem kunden die komplette jquery ui eingebaut aaber die version 1.2.7 weil bei der aktuellen version die autoplay funktion des slideshow plugins nicht funktioniert.
habe dann die komplette ui raus geschmissen und nur das slideshow plugin rein gepackt dann geht es wieder.
Die jquery version hat das einfach geblockt.

war nicht so schlimm den fehler hab ich schnell gefunden ^^

**Comment by IDragonfire** [comment]
Deswegen habe ich Issue #122 aufgemacht ;)
