### ISSUE TITLE
jQuery extract

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#122]
Wir sollten jQuery eventuell mal auslagern,
damit man auch als unerfahrende User jQuery updaten kann ...
Was meint ihr?

**Comment by Insane1990** [comment]
ja gute idee

**Comment by IDragonfire** [comment]
_push_
bitte um Kommentar von Entwicklern ...

**Comment by xDGeForcexD** [comment]
hm was heist das den es auslagern?

muss man nicht im moment einfach die _js/lib.js durch die neue version ersetzten?

**Comment by IDragonfire** [comment]
Jo aber das weiß keiner ...
Sollte man umbennenn .... oder sogar in die dzcp.js  integrieren

**Comment by xDGeForcexD** [comment]
hä aber wie soll dann ein unerfahrener user es updaten?

**Comment by Insane1990** [comment]
lib.js is doch alleinig der jquery, wo is das problem?
oder meinst dasses net ins template sondern ins cms ordner soll?
weil wenn ichs neue in mein template mache gehen die serverviewer beide nicht mehr (game und ts)

**Comment by xDGeForcexD** [comment]
dann update mal noch deine dzcp.js ...

**Comment by IDragonfire** [comment]
Die Idee ist auch gut ...
Javascript aus dem Template raus ..

**Comment by Insane1990** [comment]
warum überhaupt javascript?
wofür ist das gut?
lässt sich das nicht auch alles mit php bzw html und css umsetzen?

**Comment by IDragonfire** [comment]
einfache antwort ... nein
(mit html5 geht mehr, aber auch nicht alles)

**Comment by Insane1990** [comment]
meine ja nicht nur html, php kann aber vieles odern icht?

**Comment by xDGeForcexD** [comment]
nein es geht nicht ....
