### ISSUE TITLE
Mods/AddOn verwalten

### ISSUE THREAD

**Issue by TimoStahl** [IDragonfire/dzcp#127]
Hey,
ich bin dabei noch etwas zu bauen, um einen besseren Überblick über die installierten AddOns/Mods zu haben.

Hier soll den installer eines AddOns sich auch automatisch einfügen können, so hat es der Website Eigentümer und der Entwickler es einfacher und sehen schneller was isntallier ist oder veraltet.

Evlt können AddOns auch automatisch auf updates geprüft werden.

Bin gerade am entwickeln, ist fast fertig,

Timo

**Comment by Insane1990** [comment]
geile sache ;)

**Comment by IDragonfire** [comment]
Sowas hier?
http://www.modsbar.de/Addons/1955/addon-check/

**Comment by TimoStahl** [comment]
ja soetwas in der Art. Ich hatte eigentlich angefangen es für DZCP-Zone.de zu coden, aber jetzt wo dich mich auf version 1.6 angesproche hast, ist es ja eigentlich viel besser, einen einheitlichen Standard zu schaffen.
Zur Funktionsweise:
die eigenen Versionsnummer und Name wird lokal in einer DB gespeichert, sowie der pfad zum jeweiligen Server und andere kleinigkeiten.
Das Script greift nun auf eine txt datei auf den jeweiligen server zu, liest aus der txt die aktuelle version aus.

Aber ich lade heute Abend oder morgen, mal die erste Version hoch, dann könnt ihhr euch das mal angucken ;)

**Comment by IDragonfire** [comment]
Problem wird nur, wer es verwaltet ...
Eine Idee wäre noch das jeder für seine Mods auch github nutzt ...

**Comment by TimoStahl** [comment]
ne jeder fur seine mods, die muss er ja auch iwo hochladen, ich erklare es heute abend bzw morgen nochmal genauer

**Comment by IDragonfire** [comment]
Da bin ich dann mal gespannt ...

**Comment by TimoStahl** [comment]
Issue #135
