### ISSUE TITLE
Admin Pic für #135 Mods/AddOns verwalten

### ISSUE THREAD

**Issue by TimoStahl** [IDragonfire/dzcp#136]
Hat noch jemand ein schickes kleines Bildchen für Issue #135 Mods/AddOns verwalten? Ich habe kein schönes gefunden.

**Comment by IDragonfire** [comment]
eventuell das rss feed symbol?

http://findicons.com/files//icons/2352/frankfurt/32/feed.png

oder
http://findicons.com/files//icons/1620/crystal_project/32/agt_update_recommended1.png
http://findicons.com/files//icons/753/gnome_desktop/64/gnome_software_update_available.png
http://findicons.com/files//icons/2352/frankfurt/32/old_versions.png

**Comment by TimoStahl** [comment]
ja hmm oder ein Puzzleteil, sowas in der Art

**Comment by TimoStahl** [comment]
...mein Github Client zickt rum...

Wollte dies Bild nehmen....

http://www.geocaching.com/images/wpttypes/sm/puzzle.jpg

**Comment by IDragonfire** [comment]
Was macht den dein client?

**Comment by TimoStahl** [comment]
Done
fatal: https://github.com/blueteck/dzcp/info/refs not found: did you run git update-server-info on the server?

Ging nicht, dann habe ich das Repo local gelöscht, aber ich bekomme es nicht wieder geladen.

**Comment by IDragonfire** [comment]
Hast mich in ICQ?

**Comment by TimoStahl** [comment]
Nr gibste mir mal die Nummer?

**Comment by Insane1990** [comment]
Nimm halt nen Zahnrad als bild!

**Comment by TimoStahl** [comment]
-> Pull Request #138
