### ISSUE TITLE
Suche fixen und verbessern

### ISSUE THREAD

**Issue by TimoStahl** [IDragonfire/dzcp#142]
Ich möchte noch ein wenig an der Suchfunktion arbeiten, deshalb hier das Issue.

-die Suche achtet auf Groß/Kleinschreibung -> sollte ignoriert werden
-es werden nur News, Artikel und Sites durchsucht -> mehr Bereiche hinzufügen (z.B. Kalender und Clanwars)
-Suchbox nur übers Templte zu finden -> Suche sollte auch ohne Box im Template nutzbar sein
-bei der Forumsuche werden gesuchte Wörter Markiert -> evlt auch bei der anderer Suche nutzbar?

Das waren erstmal so die Ideen, wenn ihr noch mehr Ideen habt, schreibt sie doch mal ;)

**Comment by IDragonfire** [comment]
bitte testen

**Comment by xDGeForcexD** [comment]
leider gibt es einpaar felher
- es fehlen die übersetztungen
- sonderzeichen wie zb Ηдллιвдζ findet er nicht

**Comment by IDragonfire** [comment]
http://www.dzcp.de/forum/?action=showthread&id=15171&page=14#p137

lang fehlt

**Comment by xDGeForcexD** [comment]
hab ich doch oben schon geschrieben^^

**Comment by TimoStahl** [comment]
Bin erst ende August wieder aus dem Urlaub. Vllt mag sich das sonst jemand anderes angucken?

**Comment by TimoStahl** [comment]
#173 sind schonmal die fehlenden Sprachdateien

**Comment by acecom** [comment]
in der suche werden unveröffentlichte news artikel angezeigt! diese solltem wie bei der forum suche (forum intern) ausgeblendet werden

**Comment by IDragonfire** [comment]
da fehlt sicherlich nur ein feilter nach intern = 1 ^^

**Comment by TimoStahl** [comment]
okay das intern und unpublished ist gefixt (siehe #179)
