### ISSUE TITLE
Mods/Addons verwalten

### ISSUE THREAD

**Issue by makke81** [IDragonfire/dzcp#144]
Wenn der File auf dem Server nicht vorhanden ist gibt es eine fehlermeldung

Warning: file(http://makke81.de/versionen/versionen2.txt) [function.file]: failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in C:\xampp\htdocs\root\dzcp\admin\menu\version.php on line 219

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\root\dzcp\admin\menu\version.php on line 220

und in der liste wird die version vom vorgänger übernommen da die variable nicht neu befüllt wird.

**Comment by TimoStahl** [comment]
danke für den kleinen fix ;)
