### ISSUE TITLE
Profilfelder lassen sich nicht ausblenden

### ISSUE THREAD

**Issue by Insane1990** [IDragonfire/dzcp#145]
Auf http://bloody-angelz.eu/cms/admin/?admin=profile sind zwar Grüne Hakensymbole hinter den Profilfeldern, aber keines davon lässt sich ausblenden.

Normalerweisse wurde das ja schon gefixt, aber ist in der Aktuellen Beta noch nicht drin.

**Comment by IDragonfire** [comment]
wann hast du dir die Beta heruntergeladen und wo?

**Comment by Insane1990** [comment]
von hier?!
da sagte aber jemand es sei schon gefixt

**Comment by xDGeForcexD** [comment]
also bei mir geht alles und hab die aktuelle version von hier

**Comment by IDragonfire** [comment]
Insane?

**Comment by IDragonfire** [comment]
geht bei mir ...
