### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by makke81** [IDragonfire/dzcp#147]
bei erstellung eines neuen Links kommt die Meldung 
du musst ein weiterletungsziel angeben.

/admin/?admin=navi&do=addnavi

**Comment by xDGeForcexD** [comment]
wurde bereits behoben #126

**Comment by makke81** [comment]
Hab ich dann auch gesehen als ich das Fixen wollte^^
und irgendwie hab ich hier bei Github versehentlich nen filter aktiviert der mir nur den milestone ausgegeben hat und ich habs irgendwie nicht gepeilt.

**Comment by IDragonfire** [comment]
Links steht der milestone ... Einfach darüberfahren, dann erscheint ein x zum entfernen, oder oben irgendwo reset filter ...

**Comment by IDragonfire** [comment]
Das ist so ein Zanhrad ...
Oder oben ...
Clear all milestones ...
