### ISSUE TITLE
Vorschau und last post im Forum: funktionieren keine links

### ISSUE THREAD

**Issue by xDGeForcexD** [IDragonfire/dzcp#152]
In den ganzen vorschauen wie zb news coments oder auch im forum wenn man etwas neues postet in dem last post funktionieren keine links wie zb der link zum userprofil von dem user

**Comment by IDragonfire** [comment]
war das schon immer so oO
Oder meinst du autourl erkennung geht nicht?

**Comment by xDGeForcexD** [comment]
ich denk das ist schon immer so auch auf dzcp geht es nicht

man hat ja rechts kleine userinfo mit userlink und der geht auch nicht

**Comment by xDGeForcexD** [comment]
kann es sein das dies gewohlt ist? 
weil dafür ist die cleanautor function da aber warum ist das da hat das irgendein sinn? an der function von dem der hp kanns nicht liegen weil wenn ich die autor function benutze funktioniert es auch und der link wäre da

**Comment by IDragonfire** [comment]
also ich würde es als nicht so wichtig einstufen ..
