### ISSUE TITLE
Vorschlag: index.html verdoppeln

### ISSUE THREAD

**Issue by makke81** [IDragonfire/dzcp#155]
in der function page der bbcode.php wird ja bekantlich die Page zusammengesetzt.

währe es bei den parametern nicht möglich 

$tpl_index_show='index' einzusetzen

und das dann ganz untem im echo anstelle von index zu verwenden

sodas man dann z:B. in der forum/index.php  die pagefunktion mit $tpl_index_show='index_forum' bestücken kann.

das würde meiner meinung nach vielen helfen nicht mehr die bbcode dublizieren zu müssen und das ganze dann immer zweimal modifizieren zu müssen.

**Comment by xDGeForcexD** [comment]
find ich eine gute idee :)

**Comment by makke81** [comment]
Perfekt! 
ich hab leider momentan keine zeit deswegen nur der Vorschlag ^^

**Comment by IDragonfire** [comment]
so würde ich es auch machen ...

**Comment by hammermaps** [comment]
IDragonfire die issue kann geschlossen werden, es wurde eingebaut.

**Comment by IDragonfire** [comment]
übersehen ...
