### ISSUE TITLE
TS3 funktionieren keine Sonderzeichen

### ISSUE THREAD

**Issue by xDGeForcexD** [IDragonfire/dzcp#165]
Im TS3 Viewer funktionieren wieder keine Sonderzeichen

**Comment by IDragonfire** [comment]
müsse man nicht auch prüfen, ob es die Funktion "is_php_5()" gibt?

**Comment by xDGeForcexD** [comment]
die function gibt es die ist in der kernel.php

**Comment by IDragonfire** [comment]
ups, zu viel in der Sonne gebräunt xD
