### ISSUE TITLE
kernel.php VisitorIp function renmae

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#170]
Hammermaps könntest du die VisitorIp Funktion im kernel.php
zu visitorIp umbennen,
dass alle Methoden mit einem kleinen Buchstaben anfangen?
Oder hast du diese Methode bis jetzt nur in der bbcode benutzt?

**Comment by IDragonfire** [comment]
danke

**Comment by TimoStahl** [comment]
reference falsch, sry ;)
