### ISSUE TITLE
Kommentar-Funktionsbaustein

### ISSUE THREAD

**Issue by TimoStahl** [IDragonfire/dzcp#177]
Wie wäre es mit einer Funktion die für jegliche Kommentare genutzt werden kann?

Denn newscomments, clanwarcomments, artikelcomments sind alle fast gleich.

Und so lassen sie Mods leichter einbauen, mit einer neuen JKommentarfunktion, oder Mods die diese Kommentarfunktion modifizieren.

Was haltet ihr davon?

**Comment by IDragonfire** [comment]
nette Idee, würde aber gerne dzcp1.6 mal releasen und das ist kein Bugfix ...
Sinnvoll auf jedenfall ...

**Comment by TimoStahl** [comment]
Okay, können wir ja dann ohne Meilensteinbezug stehen lassen, die Entwicklung geht ja anschließende hier auf Github weiter oder nicht?

**Comment by IDragonfire** [comment]
ich markiere das als won't fix und man kann diese dann alle nach dem Meilenstein öffnen, k?

**Comment by TimoStahl** [comment]
kein Problem
