### ISSUE TITLE
Installer Fehler Schreibrechte

### ISSUE THREAD

**Issue by TimoStahl** [IDragonfire/dzcp#189]
Wenn man den installer ausfürht kommt ein Fehler, das keine Schreibrechte für  Dir:     /__cache vorhanden sind. Dieses Verzeichnis gibt es ja nun nicht mehr, muss korrigiert werden.

**Comment by IDragonfire** [comment]
Waeum gibt s diese Verzeichnis nicht mehr oO

**Comment by TimoStahl** [comment]
weil der im großen hammermaps update nach inc verschoben wurde

**Comment by hammermaps** [comment]
jop, hab ich verpennt
Im moment schreibe ich den installer neu^^
