### ISSUE TITLE
xfire Fehler

### ISSUE THREAD

**Issue by TimoStahl** [IDragonfire/dzcp#195]
Hey ihr, in der Userlist wird aus der users tabelle xfire abgefragt, aber kann es sein das diese spalte nicht mehr existiert, also im installer nicht angelegt wird?

**Comment by IDragonfire** [comment]
xfire wurde umstrukutiert ... wurde ursprünglich reingefutscht über hlsw ... wurde sicherlich im Installer was vergessen ;) danke^^

**Comment by hammermaps** [comment]
Habs nachgebessert, danke BlueTeck

**Comment by IDragonfire** [comment]
http://www.dzcp.de/forum/?action=showthread&id=15171&page=16#p158

**Comment by IDragonfire** [comment]
musste komplett neu installieren, dann ging es.
