### ISSUE TITLE
ADMIN: unveröffentlichte Artikel kann man nicht ansehen 

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#2]
Folgende Meldung kommt, wenn man im Adminmenü eine unveröffentlichten Aritkel ansehen möchte:

Warning: date() expects parameter 2 to be long, string given in /var/www/vhosts/templatebar.de/demo.dzcp.de/artikel/index.php on line 236

**Comment by Koma83** [comment]
Getestet und funktioniert!
