### ISSUE TITLE
ALL: Infobox Webbrowser Update 

### ISSUE THREAD

**Issue by Koma83** [IDragonfire/dzcp#20]
All: Infobox Webbrowser Update

**Comment by IDragonfire** [comment]
kann man das eventuell dynamisch auslesen?

**Comment by IDragonfire** [comment]
_push_

**Comment by IDragonfire** [comment]
wird sowieso selten genutzt:

http://www.dzcp.de/forum/?action=showthread&id=15171&page=1#p2

**Comment by Koma83** [comment]
Getestet und funktioniert!
