### ISSUE TITLE
Banner Sponsoren von Modsbar und Templatebar werden nicht angezeigt

### ISSUE THREAD

**Issue by acecom** [IDragonfire/dzcp#200]
Banner Sponsoren von Modsbar und Templatebar werden im Standart Template nicht angezeigt. (kleiner Schönheitsfehler)

**Comment by IDragonfire** [comment]
Banner gibt es auch gar nicht mehr ... und nun?
https://github.com/IDragonfire/dzcp/blob/bugfree2/_installer/conf/mysql.php#L1378

www.templatebar.de/___FILES/TBbanner/tb_468x60_2.gif
www.templatebar.de/___FILES/MBbanner/mb_468x60.gif

**Comment by acecom** [comment]
dann Close Problem liegt bei template und modsbar
