### ISSUE TITLE
link us banner dzcp fehlt / wird nicht angezeigt

### ISSUE THREAD

**Issue by acecom** [IDragonfire/dzcp#202]
link us banner dzcp fehlt / wird nicht angezeigt (Schönheitsfehler)

**Comment by IDragonfire** [comment]
https://github.com/IDragonfire/dzcp/blob/bugfree2/_installer/conf/mysql.php#L1376

Eingetragen wird er ...

**Comment by hammermaps** [comment]
Das Banner kam von http://www.dzcp.de/banner/ es existiert nicht mehr, hat einer noch das Banner?

**Comment by acecom** [comment]
würde den link ändern und den banner aus dem cms erstmal nehmen /banner/partners/dzcp.gif oder richy muss mal schaun was mit den bannern auf den Servern los ist bei Sponsoren wird der modsbar und templatebar banner auch nicht angezeit alternative wieder aus cms banner/partners/tb_88x32.gif und banner/partners/mb_88x32.gif
