### ISSUE TITLE
Admin - User hinzufügen: lang Fehler

### ISSUE THREAD

**Issue by acecom** [IDragonfire/dzcp#204]
unter admin -> user hinzufügen steht global uplodpic müsst aber profilfoto heißen

muss bestimmt ein neuer platzhalter erstellt werden  in der lang. mit profilfoto

sin voll wer auch ein Feld über das man auch den Avatar beim anlegen des users  gleich uploaden könnet

**Comment by IDragonfire** [comment]
Ort:
https://github.com/IDragonfire/dzcp/blob/bugfree2/inc/lang/languages/deutsch.php#L1709

**Comment by acecom** [comment]
ja ich weiß aber an der stelle wer eine andere Bezeichnung für die User besser am besten wer einen neuen Platzhalter dort zu definieren

**Comment by acecom** [comment]
unter admin -> user hinzufügen steht global uplodpic müsst aber profilfoto heißen
in zeile 70 der admin/menu/adduser.php folgendes ändern "pbild" => _config_c_upicsize, ändern in "pbild" => _profil_ppic,
