### ISSUE TITLE
Clanwars  Statusbalken Win / Draw / Lose zählt falsch

### ISSUE THREAD

**Issue by acecom** [IDragonfire/dzcp#207]
Unter Clanwars addiert der Statusbalken zbsp.  alle lose.

2 lose = 200% was den balken rechts aus dem template laufen lässt

**Comment by IDragonfire** [comment]
Hast du ein Beispiel, Screenshot?

https://github.com/IDragonfire/dzcp/blob/bugfree2/clanwars/index.php#L36

**Comment by acecom** [comment]
http://axx-xxm.de/dzcp16/clanwars/

**Comment by IDragonfire** [comment]
We vermutet wird es praktisch nicht auftreten. Dieses Problem tritt auf, wenn man bei einem Clanwar Punkte einträgt und den Termin in der Zukunft liegt.
