### ISSUE TITLE
CORE: Kommentare zu ungültigen ID´s möglich

### ISSUE THREAD

**Issue by makke81** [IDragonfire/dzcp#23]
Anfangen werd ich heute mit News und Artikel

sonnstige fehlfunktionen werden demnächst nachgetragen.

**Comment by makke81** [comment]
UserGB und Clanwar kommentare sind ebenfalls mit diesem fehler behaftet.

**Comment by IDragonfire** [comment]
ist jetzt alles gefixt?
Irgendwo ging es doch noch  oder?

Suche nach "page/comments_show" ergab Kommentarfunktion in:

artikel
clanwars
news
user

**Comment by makke81** [comment]
und all diese dateien hab ich auch gepusht ^^

**Comment by makke81** [comment]
die ungültige forenpost geschichte mach ich mich jetzt dran.

**Comment by IDragonfire** [comment]
Das fällt auch unter diesem Issue, oder?

**Comment by IDragonfire** [comment]
es ist noch möglich zu ungültigen Kategorien zu posten ...
das muss noch abgefangen werden  ...
sollte in einem Query gehen ...

**Comment by acecom** [comment]
mit einer änderung im link wird der posst in der forumübersicht falsch zugeordnet (Counter)
ändert man im forum auf der tinymceseite die kid nummer im browser sowird diese posst in der falschen kategorie hinzugezählt.

bsp. betaseite:
http://beta.dzcp.de/forum/index.php?action=post&do=add&kid=7&id=1

ändert man in diesem link kid=7 auf kid=4 (kategorie 4 Spam)

http://beta.dzcp.de/forum/index.php?action=post&do=add&kid=4&id=1 (enter)

lädt die seite neu und verfasst einen posst wird dieser richtig eingetragen aber im forum als posst in der Kategorie (Spam) +1 hinzugezählt
in der übersicht sieht man nun bei spam threads 0 beiträge 1
