### ISSUE TITLE
JQuery Veraltete version 

### ISSUE THREAD

**Issue by makke81** [IDragonfire/dzcp#28]
das Jquery sollte geupdatet werden und auch Updatebar gehalten werden.

infolge dessen sollte auch die Lightbox unabhängig von Jquery abgelegt werden damit man diese ebenfalls leichter seperat Updaten kann.

**Comment by IDragonfire** [comment]
gute arbeit .. hast das alles getestet?

**Comment by Koma83** [comment]
Getestet und funktioniert!
