### ISSUE TITLE
CORE: LastLogin 

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#3]
Last Login wird nicht richtig gesetzt,
bzw. ist reduntant in der Datenbank und wird nicht richtig aktualisiert/genutzt:

userstats.lastlogin
user.time

Eins wird nur bei der Session/Login gesetzt,
dass andere erst wenn man glaubig "Temopräre Neuerungen löschen" drückt.

Viele Mods nutzen dies falsch ...

**Comment by HellBz** [comment]
https://github.com/IDragonfire/dzcp/blob/master/user/index.php#L907

Also soweit ich es weis wird der lastlogin in der User-Db gesetzt und in der Userstats dann übernommen, wenn man in der Userlobby auf tem. neuerungen löschen klickt soweit habe  ich das herrrausgefunden.

Fehler vorbehalten
