### ISSUE TITLE
Core: Kommentare als unregistrierter Gast möglich

### ISSUE THREAD

**Issue by makke81** [IDragonfire/dzcp#30]
in den Artikeln ist es möglich kommentare als unregistrierter user zu verfassen
in den News ist es möglich kommentare als unregistrierter user zu verfassen

im Forum ist es möglich neue Threads zu eröffnen.

habe das eben gefixt Upload folgt gleich.

**Comment by IDragonfire** [comment]
Also bei Clanwars habe ich es gefixt ... d.h. da fehlt es überall :-( ...

**Comment by IDragonfire** [comment]
Hier die Issue dazu:

#12 Clanwars fix
#7 Man kann unregistriert Clanwarkommentare eintrage

**Comment by Koma83** [comment]
Getestet und funktioniert!
