### ISSUE TITLE
CORE: LightboxUpdate, bzw. Image Resize repair

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#32]
LightboxUpdate, bzw. Image Resize reparieren
Macke hat da schon was in #30 gemacht ....
Sollten wir das Image REsize noch für Forum und Co trennen?

**Comment by makke81** [comment]
mit immage resize ist die grössenanpassung von zu grossen bildern gemeint?
wenn ja dann währe bis freitag nen hinweis auf was genau da nicht stimmt nicht schlecht.

**Comment by IDragonfire** [comment]
Manchmal, meine z.b. wenn die bilder nicht geladen werden können funktioniert es nicht ... wenn du image resize für das forum passend einstellst, werden die newsbilder auch resized. So hat man keine großen newsbilder oder muss im forum  auf das resize verzichten ...

**Comment by makke81** [comment]
dann sollten wir das splitten, sollte nicht so ein grosses problem sein,
in der bbcode.php
 zeile 54 wird die variable definiert,
 zeile 2301 u. 2311 tauchen sie dann in den java_vars auf.
 jetzt müsste man nur noch unterscheiden zwischen Forum und News etc.

**Comment by IDragonfire** [comment]
Gestern wurde auch noch angesprochen, dass große Bilder in der Lightox (wenn man bei Clanwars oder Galerie auf ein Bild klickt)  nicht verkleinert werden (riesig erscheinen). Müssten wir mal testen ob dies noch immer ist ...

**Comment by makke81** [comment]
die lightbox lässt bilder in Original grösse erscheinen was irgendwie der sinn des ganzen ist, wenn jetzt jemand mit 1920er auflöung nen screen hochläd und sich dann jemand mit ner 1024er sie ansieht ist das also völlig normal das die bilder riesig aussehen. 
da müssten wir dann schauen das die bilder je nach bildschirmgrösse skaliert werden, was man eventuell über css regeln könnte?

**Comment by IDragonfire** [comment]
Bin mir nicht sicher ob es darüber geht ...aber irgendwie muss es ja gehen ...
Wäre sonst ja irgendwie blöd, oder?

**Comment by makke81** [comment]
ich hab das jetzt soweit das es auf 90% der browsergrösse geschrupft wird
ich lad das dann nachher zusammen mit dem anderen issue hoch.

**Comment by makke81** [comment]
getestet hab ich das hier http://repo.makke81.de/gallery/

**Comment by IDragonfire** [comment]
das sieht doch sehr gut aus ...

**Comment by Koma83** [comment]
Getestet und funktioniert!
