### ISSUE TITLE
Glossar: Glossarwords split text

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#34]
Glossarwörter zerreißen Text (aus Interesse wird z.b. INT eresse)

Problem # 2:
http://www.dzcp-zone.de/forum/?action=showthread&id=1907

**Comment by IDragonfire** [comment]
Wenn das alles war, wäre es cool xd

**Comment by IDragonfire** [comment]
Glossar geht nicht mehr im Forum...
http://www.dzcp.de/forum/?action=showthread&id=15171&page=7#p70

**Comment by makke81** [comment]
Hmmm... dabei hab ich das ganze im Forum getestet.

ich schau mir das Morgen nochmal an wenn ich mein lokales system geupdatet hab.

**Comment by IDragonfire** [comment]
gibt es was neues?

**Comment by makke81** [comment]
Ich hab das ganze gerade mal bis auf das Checkin zurück gesetzt und bin zum Schluss gekommen das das im Forum noch nie funktioniert hat.

Hab es daraufhin auf meiner Supportseite getestet die ja noch mit orignal DZCP 1.5.5.2 Arbeitet, da ist es auch nicht im Forum eingebunden.
