### ISSUE TITLE
News: show only one category

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#35]
Newskategorien gehen nicht richtig (fix übernehmen und template updaten)

http://www.dzcp.de/forum/?action=showthread&id=15088&page=1

**Comment by makke81** [comment]
der Fix blendet eber nicht die Sticky-News aus den anderen kategorien aus 
ich hab da mal nen bissl mehr gemacht.

**Comment by IDragonfire** [comment]
Die Positionierung der Dropdown Box ist nicht ganz gelungen,
ich bin für rechts, oder mittig, was meinen die anderen?

Kannst ja mal auf beta.dzcp.de sehen

**Comment by makke81** [comment]
Die war glaube ich MIttig, ich hab die extra nach links gesetzt damit die da nicht mitten drin rumfleucht, Rechts ist aber auch OKE.

**Comment by IDragonfire** [comment]
Habe ich in 199b4f44ebe1f0e04f832fd2d97d47aeffa35141 nach unten verschoben ...
