### ISSUE TITLE
Newletter: wrong hyperlink

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#36]
Link wird gekürzt und wird falsch

http://www.dzcp.de/forum/?action=showthread&kid=6&id=15060&page=1#p3

**Comment by Koma83** [comment]
Habe im standart mal versucht den link http://www.dzcp.de/forum/?action=showthread&kid=6&id=15060&page=1#p3
in der Newsletter zu versenden ging bei mir ohne probleme.

Vieleicht probiert es noch mal jemmand anderes gruss Andre

**Comment by IDragonfire** [comment]
Also ich kann den Fehler auch nicht nachvollziehen, makke?

**Comment by makke81** [comment]
Ich probier das Mittwoch nochmal aus, ich versende so selten Newsletter^^

**Comment by IDragonfire** [comment]
So sieht es auch bei mir aus xd

**Comment by IDragonfire** [comment]
Neuigkeiten?

**Comment by IDragonfire** [comment]
http://www.dzcp-addons.eu/forum/?action=showthread&id=61&page=1#p4

**Comment by IDragonfire** [comment]
Also HellBz meint,
interne Links werden in der email nicht richtig umgewandelt,
bzw. das Mailprogramm weiß die Domain nicht ...
