### ISSUE TITLE
CORE: TinyMCE

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#4]
TinyMCE erkennt den Text beim senden nicht mehr ...

möglicher Fix?
http://daveymorris.co.uk/web-development/tinymce-and-internet-explorer-9-fix-again/

mobile Fix?
https://github.com/IDragonfire/dzcp/issues/11

**Comment by IDragonfire** [comment]
FileManager möglicherweise vom CKEditor

http://ace-com.de/dzcp1552/tinymce.rar

Dank an acecom

**Comment by HellBz** [comment]
Evtl. Plugins mit einbinden ( For FREE ) GNU GPL

http://www.binpress.com/app/tinymce-image-manager-and-editor/781
http://www.binpress.com/app/tinymce-youtube-iframe-embed--plugin/667

**Comment by IDragonfire** [comment]
Anmerkung:

Wenn die unter GNU GPL stehen,
dann müssen wir dzcp auch unter GNU GPL stellen  ...
Wo ich ja nichts gegen hätte ... aber da müsste man mit Richy sprechen ...
LGPL wäre besser ...

**Comment by acecom** [comment]
TinyMce ist nicht sotief im DZCP verbaut wie erst angenommen. Der Editor wird nur über das JavaScript (!!!) eingebunden in der dzcp.js File. 
codezeile:  
var inst = tinyMCE.getInstanceById(thisID);
          $('#' + thisID).attr('value', inst.getBody().innerHTML);
        }
Der filemanager kann 1zu1 beibehalten werden wichtig ist nur dadrauf zuachten das im tinymcs odner themes->advanced->images erhaltenbleibt da dort das icon für den uploader abgelegt ist.

**Comment by makke81** [comment]
Ich dachte der Filemanager macht auch probleme?
wenn das nicht der fall ist dann versuchen wir den alten natürlich beizubehalten.

**Comment by IDragonfire** [comment]
Wie ich schon einmal gesagt habe ... Jeder hat etwas dazu gemacht ... Ihr solltet eure Erkenntnisse mal sammeln ... am besten hier oder mal ein Termin dafür ansetzen und dann hier posten was daraus geworden ist ...

**Comment by Koma83** [comment]
Makke und Ich haben den TinyMCE schon auf die neue stabile version 3.3.9.4 geupdatet und sind noch bei ihn zu verbesser.

http://www.phpletter.com/Demo/Tinymce-Ajax-File-Manager/

**Comment by IDragonfire** [comment]
Unter Chrome hat man ein zu hohen Chrome Zeilenabstand:

http://www.imagebanana.com/view/qmeaifog/20120316_191435.jpg

**Comment by makke81** [comment]
für den fall das du keine änderungen siehst,
http://support.google.com/chrome/bin/answer.py?hl=de&answer=95582

**Comment by IDragonfire** [comment]
n1 werde ich gleich testen ;) ... Habt ihr das Syntax Error Problem gelöst?

**Comment by IDragonfire** [comment]
Nach dem Cache reset ging es, super arbeit !!!

**Comment by IDragonfire** [comment]
@Koma83 
Hast du schon den Support angeschrieben?

Geht um folgendes Problem:
http://www.imagebanana.com/view/b65arxzi/20120318_223354.jpg

Man bekommt beim Uploaden manchmal eine Meldung (alert)
Unexpected Syntax Error: { Property List ... (korrigiert mich wenn ich falsch liege ...)

**Comment by Koma83** [comment]
Habe den Support angeschrieben warte noch auf rückmeldung.

Gruß Koma

**Comment by IDragonfire** [comment]
Hat der Support sich gemeldet?

**Comment by IDragonfire** [comment]
line-height: 120%; entfernen ...
https://github.com/IDragonfire/dzcp/blob/master/inc/_templates_/version1.5/_css/stylesheet.css#L14

fixt Zeilenbug ... dank an Koma

**Comment by Koma83** [comment]
Ups die line-height nicht entfernen sonder ändern in line-height: 1.2; 

Gruß Koma

**Comment by IDragonfire** [comment]
Häh .. Warum nicht entfernen ? 1.2 ist doch das gleiche in grün

**Comment by makke81** [comment]
da fehlen jetzt nur noch die schreibrechtevergaben in dem installer, das mach ich aber wenn ich es schaffe gleich noch fertig.

**Comment by IDragonfire** [comment]
die müssen wir so oder so mal überprüfen ...

**Comment by Koma83** [comment]
Brauche mal hilfe bei diesem code:

function selectFile(url)
{
     var fileName = '';
     if(url.length == 0)
     {
      fileName =  ''; 
     }else
     {
        var pos = url.lastIndexOf("");
        if(pos != -1)
        {
             fileName = url.substr(pos,url.length);
        }else
        {
           fileName = url;
        }
     }
      window.opener.document.getElementById(elementId).value = fileName;
      window.close() ;

}

er soll nicht die komplette url nehmen sondern nur ../inc/tinymce_files/

THX Koma

**Comment by makke81** [comment]
Ich bin am Samstag wieder da, dannn können wir wenn du willst das mal gemeinsam durchgehen.

**Comment by IDragonfire** [comment]
Ok, dann bis SA

**Comment by Koma83** [comment]
geht klar^^

**Comment by Koma83** [comment]
hi sry konnte gestern nicht kommen bin gerade an meinem handy muss mir morgen ein neues netzteil für mein pc kaufen der geht nicht mehr an hoffe es liegt da drann.

Hat einer von euch sich den code mal angesehen?

Gruss Andre

**Comment by makke81** [comment]
Koma, kein thema ich hab immer mal was anderes zu tun weshalb ich jetzt nicht unnötig gewartet habe^^

der Code alleine bringt nicht viel da ich den zusammenhang verstehen müsste, 
wenn du heute Abend schon nen neues Netzteil hast können wir uns das dann zusammen ansehen.

**Comment by Koma83** [comment]
Hi sry kann erst ab heute netzteil habe ich gerade erst bekommen also ab heute bin ich wieder da.

MFG Koma

**Comment by IDragonfire** [comment]
Mi abend? Rühre da vorher nichts an ...

**Comment by Koma83** [comment]
So fertig zum testen sind hier die daten

Testseite:http://xite.gameserver2go.de/dzcp/

Name:test
pw:test

**Comment by IDragonfire** [comment]
ohne Secure Fix wird das nicht übernommen ...
z.B.:

/inc/tinymce/plugins/ajaxfilemanager/ajax_delete_file.php?delete=../../../../inc/tinymce_files/008.png

**Comment by IDragonfire** [comment]
0ad1d8ef38 im Repo übernommen

**Comment by Koma83** [comment]
Getestet und funktioniert!
