### ISSUE TITLE
JAVASCRIPT: Compress dzcp.js

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#45]
neue dzcp.js komprimieren

**Comment by makke81** [comment]
http://dean.edwards.name/packer/

hattest du die letzten änderungen nicht direkt komprimiert?

**Comment by IDragonfire** [comment]
Meine nicht, siehst ja ;)
https://github.com/IDragonfire/dzcp/tree/master/inc/_templates_/version1.5/_js
Aber hatte nur etwas daraus entfernt (das alte Googlr API Zeugs)

**Comment by IDragonfire** [comment]
k, meine Änderungen waren schon drinnen ...
