### ISSUE TITLE
Installationsfertig machen

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#47]
Dir:     /__cache
 File:    /rss.xml

 Dir:     /inc/images/uploads/taktiken
 Dir:     /inc/images/uploads/useravatare
 Dir:     /inc/images/uploads/usergallery
 Dir:     /inc/images/uploads/userpics

 Dir:     /inc/tinymce_files

 Dir:     /inc/tinymce/plugins/ajaxfilemanager/session
 Dir:     /inc/tinymce/plugins/ajaxfilemanager/session/gc_counter.ajax.php

**Comment by IDragonfire** [comment]
TODO: inc/mysql.php hinzufügen

**Comment by IDragonfire** [comment]
File: /rss.xml
Dir: /inc/tinymce/plugins/ajaxfilemanager/session
Dir: /inc/tinymce/plugins/ajaxfilemanager/session/gc_counter.ajax.php

hinzufügen !!!

**Comment by acecom** [comment]
für "forum: sort subkat manualy" fehlt im installer / update die änderung in der datenbank

**Comment by IDragonfire** [comment]
bitte immer auf das Issue referenzieren ...
mit Route dann Issuenummer:
#71

Installer ist angepasst ...

https://github.com/IDragonfire/dzcp/blob/master/_installer/conf/mysql.php#L1440

**Comment by acecom** [comment]
Prefix: ist ʺ_dzcpʺ sollte aber ʺdzcp_ʺ sein

**Comment by IDragonfire** [comment]
Mein Fehler ...
https://github.com/IDragonfire/dzcp/blob/7b9b5e85348e2e028fd5f350d5244bd0b3d93580/_installer/html/mysql_data.php#L16

**Comment by IDragonfire** [comment]
http://www.dzcp-addons.eu/dev-zone/index_n.html

**Comment by IDragonfire** [comment]
Brauchen ein grobes readme ...

Changelog (GANZ AM ENDE):

https://docs.google.com/document/d/1UGwdJ9NxPd86yYvEyHwkaa23lXP0TTZbKS6BnZSvFIQ/edit

Vorlage für readme:

http://pastebin.com/iErnM98x
