### ISSUE TITLE
Forum: Forum Suche (highlight wird nicht ressetet)

### ISSUE THREAD

**Issue by makke81** [IDragonfire/dzcp#5]
wenn die $_GET['hl'] nicht mehr übergeben wird muss der Cookie gelöscht werden.

**Comment by IDragonfire** [comment]
Bzw. die Session:
https://github.com/IDragonfire/dzcp/blob/master/forum/index.php#L416

gesetzt wird es hier:

https://github.com/IDragonfire/dzcp/blob/master/search/index.php#L78

und auch hier

https://github.com/IDragonfire/dzcp/blob/master/search/index.php#L82

und auch hier:

https://github.com/IDragonfire/dzcp/blob/master/search/index.php#L133

**Comment by IDragonfire** [comment]
Der Bug tritt nur beim Text suchen auf, nicht beim Autor suchen !!!
