### ISSUE TITLE
TinyMCE: Insert Image width problem

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#51]
http://www.dzcp.de/forum/?action=showthread&id=15171&page=1#p10

Die Pfadboxen beim Bilder einfügen Dialog des TinyMCE Editors ist zu breit.

**Comment by IDragonfire** [comment]
http://img210.imageshack.us/img210/5892/1338887356960.jpg

**Comment by acecom** [comment]
die breite der inputfelder würde koregiert (200px auf 180px)

**Comment by IDragonfire** [comment]
Pusht du es, oder sehe ich es wieder mal nicht xd
