### ISSUE TITLE
JS: Chrome Resize Bug

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#60]
If you press F5 into Chrome ...
resize didn't work ...

http://hustoknow.blogspot.de/2010/10/chrome-and-jquery-ui-min-height-issue.html
http://stackoverflow.com/questions/6504982/jquery-behaving-strange-after-page-refresh-f5-in-chrome

**Comment by IDragonfire** [comment]
Meine Lösung wäre:

``` javascript
// load global events
  $(document).ready(function() {
    DZCP.init();
    DZCP.resizeImages();
  });
```

durch

``` javascript
// load global events
  $(document).ready(function() {
    DZCP.init();
  });

// load global events
  $(document).load(function() {
    DZCP.resizeImages();
  });
```

erestzen. Habe allerdings gerade keinen Zugriff auf ein Live System.

**Comment by xDGeForcexD** [comment]
ich habs mal bei mir getestet auf chrome, firefox und ie leider funktioniert es bei keinem dadurch geht die function garnicht mehr

**Comment by IDragonfire** [comment]
Muss ich mir heute abend mal in Ruhe anschauen ...
Habe glaubig einen Fehler gemacht ..

``` javascript
// load global events
  $(document).ready(function() {
    DZCP.init();
  });

// load global events
  $(window).load(function() {
    DZCP.resizeImages();
  });
```

geht das?

**Comment by IDragonfire** [comment]
so bei mir geht es ... ich checke es mal bei dir ein ;)
