### ISSUE TITLE
Gameserver: PW is visible for everybody

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#61]
http://www.dzcp.de/forum/?action=showthread&id=15192&page=1

Wie bekomme ich es hin, dass das eingetragene Passwort NUR für Member sichtbar ist?
Weil User und Unregistrierte sehen es momentan und das ist nicht so gut.

**Comment by IDragonfire** [comment]
n1

**Comment by xDGeForcexD** [comment]
soll ma es vill so machen das es nach permission abfragt? sodass der admin entscheiden kann welcher user/gruppe es sehen darf?

**Comment by IDragonfire** [comment]
Kan man machen,
dafür müsste man aber wieder einiges beim User editieren und Co umschreiben ...
Oder man sagt einfach,
Aber Level Trial sieht man es ...

**Comment by xDGeForcexD** [comment]
eigentlich muss man nichts umschreiben man muss einfach eine neue spalte in der permission einfügen und dann einfach permission('gs_pwshow') und in der bbcode noch eine kleinigkeit machen dann ist es auch schon fertig ich werds nach mach mal dann kannste es dir ja mal anschauen

**Comment by IDragonfire** [comment]
Dann musst noch im Installer die Update Funktion erweitern,
sowie den Installer ansich und für jede Sprache einen Eintrag in der lang.

Aber hast Recht,
so viel ist es nicht ...
