### ISSUE TITLE
Contacts: Notification

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#63]
hybernate:
Wenn man als unregistrierter ein fight us ausfüllt erhält der admin keine nachricht. 
Füllt man das ganze als registrierter user aus wird die nachricht gesendet.

**Comment by IDragonfire** [comment]
Ich bekomme nach dem Absenden immer ein:

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in D:\xampplite\htdocs\dzcp\git\inc\bbcode.php on line 770

**Comment by IDragonfire** [comment]
Die Benachrichtigung wird nur an Leute geschickt, welche wirklich das Recht haben ...
der Superadmin hat dies in der Regel nicht ...

**Comment by IDragonfire** [comment]
ALSO:
Es liegt daran, das der Rang "Leader" nicht das Recht hat "FightUs Formulare zu empfangen"
Der Leaderrang sollte das eigentlich haben ..

**Comment by IDragonfire** [comment]
"mysql_fetch_array() expects parameter 1 to be resource, boolean given in" liegt an

``` php
while($get = _fetch($qry))
```

sollte:

``` php
while($get === _fetch($qry))
```

sein

**Comment by makke81** [comment]
Wenn ich Freitag dazu komme fix ich das, ich hatte das schonmal bei jemandem gefixt, hoffentlich ind ich das wieder, andernfalls müsste sich jemand anders darum kümmern da ich die Wochen drauf scheiss schichten hab und zu nichts kommen werde.

**Comment by IDragonfire** [comment]
Aus meiner Sicht wäre alles gefixt (muss man nur überall = durch === ersetzen ...) man müsste nur nachschauen, dass der "Leader" Rang beim Installieren "Fight Us" empfangen erhält ...
