### ISSUE TITLE
Admin neue User erstellen

### ISSUE THREAD

**Issue by xDGeForcexD** [IDragonfire/dzcp#64]
Folgender fehler kommt wenn man ein neuen User übers Admininterface erstellen möchte:

MySQL-Query failed:

ErrorNo = 1364
Error = Field 'whereami' doesn't have a default value
Query = INSERT INTO users SET `user` = 'test', `nick` = 'Test Account', `email` = 'daniel@xdgeforcexd.eu', `pwd` = '6494522c14582194fb3f70a5822ed618', `rlname` = '', `sex` = '1', `bday` = '', `city` = '', `country` = 'de', `regdatum` = '1340021563', `level` = '1', `time` = '1340021563', `gmaps_koord` = '', `status` = '1'

**Comment by IDragonfire** [comment]
Liegt an der MYSql Version ... Dort ist NOT NULL eingetragen

**Comment by xDGeForcexD** [comment]
ok
