### ISSUE TITLE
Forum: intern vote get public after edit

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#65]
GottesMentor:
wenn man im internen forum ein vote einbindet und diesen thread nun editiert, ist der interne vote nicht mehr intern

**Comment by hybernate** [comment]
das votingsystem ist im internen forum abgeschaltet.

if($fget['intern'] == "1") $intern = 'checked="checked" disabled="disabled"';

der button wird deaktiviert. dadurch ist es standartmässig gar nicht möglich im internen forum eine umfrage einzubinden.....

Das wurde also bearbeitet und ist kein standart.

dahingegen funktioniert die vorschau funktion nicht und gibt einen fatal error aus. Fehler hab ich bereits gefixxt muss ich nur später hier einfügen.

**Comment by xDGeForcexD** [comment]
ne das ist schon standard drin habs eben selbst auf meiner test page getestet.

Die umfrage wird public nach dem editieren und es besteht ein weitere bug wenn man es ediert dann wird ein neuer vote gestartet und der ist dann intern

**Comment by IDragonfire** [comment]
Ich sagte, das komplette Vote Modul ist nicht sauber gecodet...

**Comment by IDragonfire** [comment]
also ich habe den Bug nicht ...

die Checkbox wird korrekt gesetzt:
https://github.com/IDragonfire/dzcp/blob/master/forum/index.php#L689
und die Datenbank korrekt geupdated:
https://github.com/IDragonfire/dzcp/blob/master/forum/index.php#L917
(auch wenn der Code blöd formatiert ist)

**Comment by xDGeForcexD** [comment]
hm ich hab ihn weiterhin

bist du das auf beta.dzcp.de mit dem thread test um 22:49 wenn ja du bist nicht im internen forum^^

**Comment by IDragonfire** [comment]
ach, mist, habe ich verlesen xD

**Comment by IDragonfire** [comment]
Sollte jetzt gehen ... beta Seite update ich morgen ... mit hybernates Forum Sorter ...
