### ISSUE TITLE
Squad Award System Link description replace http:// don`t working with www. only

### ISSUE THREAD

**Issue by hybernate** [IDragonfire/dzcp#66]
Versuchte eben bei einem "neuerstellten" Team ein Award hinzu zufügen. Das Team wird mir aber nicht zur Auswahl angeboten. Nur der Testsquad wird mir zur Auswahl angeboten.

Desweiteren soll man den Link von dem Event angeben: Wenn man mit "www." anfängt, erkennt der das nicht als URL und verlangt weiterhin nach einem gültigen Link.

Quelle: http://www.dzcp.de/forum/?action=showthread&id=15171&page=3#p27

**Comment by xDGeForcexD** [comment]
hm ich versteh das nicht ganz :(

wo ist in dzcp ein Event System? ist das Ereignisse eintragen bei Kalender? wenn ja wo muss man da ein link einfügen? oder soll der das automatisch aus der Beschreibung umwandel zu einem link?

**Comment by xDGeForcexD** [comment]
hm kann leider nicht editieren hat sich aber erledigt hab's gefunden^^

**Comment by xDGeForcexD** [comment]
hm sry das ich schon wieder schreib aber ich hab es mal bei mir getestet und es wurden alle Awards eingetragen ich hab mit http, ohne http und www und ohne http und Domain getestet und das hat alles funktioniert

**Comment by hybernate** [comment]
oh sorry ich hab das issue fehlerhaft eingetragen das war meine schuld!!!!! ich editiere das

**Comment by IDragonfire** [comment]
Häh? Ich check nichts xD

**Comment by hybernate** [comment]
musst auch net alles verstehen :-P ne es geht da um das award system und links einfügen ich hatte das falsch deklariert das es da um das event system ginge.
