### ISSUE TITLE
TS3 Update

### ISSUE THREAD

**Issue by hybernate** [IDragonfire/dzcp#68]
Hab da auch nochwas was verbuggt ist z.B der Teamspeak Viewer mit Eingeloggt seit und AFK seit genauso wie die Uptime des Servers gehn seit ich DZCP habe falsch bis garnicht ^^.gif.

Gruss

Devil

Quelle: http://www.dzcp.de/forum/?action=showthread&id=15171&page=4#p33
#### 

[...]r TS-Viewer liest die subchannels nicht richtig aus...

den ersten subchannel ja, aber wenn man dann in dem subchannel noch welche hat, zeigt der viewer sie als normale subchannels....

beispiel:
Hauptchannel
     |**Subchannel
          |** Sub-Subchannel2
          |__ Sub-Subchannel3

Zeigt der viewer nur so an:
Hauptchannel
      |__Subchannel
      |__Sub-Subchannel2
      |__Sub-Subchannel3

Quelle: http://www.dzcp.de/forum/?action=showthread&id=15171&page=4#p37

**Comment by IDragonfire** [comment]
http://www.dzcp.de/forum/?action=showthread&id=15171&page=4#p37

hinzugefügt

**Comment by xDGeForcexD** [comment]
Nur als zwischen info ich arbeite grad an den Einglogt seit, afk seit, server seit zeiten funktioniert auch^^ werde morgen dann noch die welcome message fertig machen und dann lad ich es mal hoch

Demo: http://test.xdgeforcexd.eu/DZCP/beta/teamspeak/

**Comment by hybernate** [comment]
oh das sieht schon mal gut aus finde ich. war viel fehlerhaft?

**Comment by xDGeForcexD** [comment]
hm wenn man jetzt es so sieht nicht xD habs mir nur die ganze zeit so schwer gemacht

hab jetzt in der ts query:
times in die clientlist eingefügt und beim time converter days eingefügt

bei der index:
die variablen eingfügt 

und das wars

**Comment by xDGeForcexD** [comment]
so habs mal hochgeladen wegen den subchannels müsste jemand anders schauen da ich nicht weis wie ich das machen kann :(

**Comment by IDragonfire** [comment]
Das Problem, dass kann ja ziemlich tief gehen ...
wird halt hässliches html xD

**Comment by hybernate** [comment]
bevor ihr "hässliches html" macht überlasst die html geschichte lieber mir ^^

**Comment by IDragonfire** [comment]
Ich meine der TS-Viewer ist noch im Tabellen Layout ...
und man müsste es entweder so machen,
oder alles auf div umstellen,
ich kümmer mich erst um #65
btw. hybernate wolltest du meine blöde neue cut Funktion rausnehmen?
oder soll ich das machen?

**Comment by hybernate** [comment]
ich würde den viewer auf div schreiben ist einfach sauberer.
ich mach die cut funktion. bin gerade am forum dran der sortiert irgendwie nicht richtig... bring alles durcheinander ^^

**Comment by xDGeForcexD** [comment]
ein weitere bug ist das wenn man auf ein channel drückt dann solte man ja eingeltich die channel infos bekommen aber meisten ist noch der cache vom teamspeak drin und deshalb werden die channel infos nicht angezeigt

**Comment by xDGeForcexD** [comment]
ein weitere bug ist das er keine sonderzeichen wie zb ▌☆ ★ anzeigt

**Comment by xDGeForcexD** [comment]
hab gute narichten ich hab es jetzt wahrscheinlich den channelbaum hinbekommen ich arbeite nun dran es in dzcp einzubauen ;)

**Comment by IDragonfire** [comment]
also geht hier jetzt alles?

**Comment by xDGeForcexD** [comment]
die Sonderzeichen fehlen noch und ich würd gern noch die Channel und User icons machen

**Comment by IDragonfire** [comment]
schaffst du es bis morgen?
Helfe gleich hybernate und wollte dann mergen ...

**Comment by xDGeForcexD** [comment]
die icons sollte ich morgen hinbekommen

**Comment by xDGeForcexD** [comment]
die icons sind nun fertig bin aber noch dran den channel join zu fixen
demo: http://test.xdgeforcexd.eu/DZCP/beta/teamspeak/

**Comment by xDGeForcexD** [comment]
spacer Tutorial
Standardicon richtig linken
Msg File nicht vorhanden
lösung für Gast Query Bann

**Comment by IDragonfire** [comment]
http://pastebin.com/mP7EUgTg

**Comment by IDragonfire** [comment]
``` php
<?

    /*          


                $flags = array();
                if($channel["channel_flag_default"] == 1) $flags[] = '16x16_default.png';
                if($channel["channel_needed_talk_power"] > 0) $flags[] = '16x16_moderated.png';
                if($channel["channel_flag_password"] == 1) $flags[] = '16x16_register.png'; */

        $nametest = substr($channel['channel_name'] ,0,7);
        if( $nametest == "[spacer" || $nametest == "[cspace" || $nametest == "[lspace" || $nametest == "[rspace" || $nametest == "[*space" )
                  {
                  $searchpatterns = array ("#\[spacer.]#siU","#\[spacer]#siU","#\[Spacer.]#siU","#\[Spacer]#siU","#\[.spacer.]#siU","#\[.spacer]#siU","#\[.Spacer.]#siU","#\[.Spacer]#siU");
          $channel['channel_name'] = preg_replace ($searchpatterns, null, $channel['channel_name']);
          $iconshowyn = '';
          }
        else
          {
          $iconshowyn = '<img src="../inc/images/tsicons/'.$icon.'" alt="" class="tsicon" />&nbsp;';
          }

        $subchannels = ($sub ? '<img src="../inc/images/tsicons/trenner.gif" alt="" class="tsicon" />' : '').$iconshowyn.'<a href="'.($tpl ? '?cID='.$channel['cid'].'' : 'javascript:DZCP.popup(\'../teamspeak/login.php?ts3&amp;cName='.rep2($channel['channel_name']).'\', \'420\', \'100\')').'" class="navTeamspeak" style="font-weight:bold;white-space:nowrap" title="'.rep2($channel['channel_name']).'">'.rep2($channel['channel_name']).' '.$this->renderFlags($flags).'</a><br />';

/* 
        $out .= show(($tpl ? $tpl : "menu/teamspeak_subchan"), array("subchannels" => $subchannels));
        $out .= (count($this->_userDatas) > 0 ? $this->renderUsers($channel["cid"], $sub) : '') . $this->renderChannels($channel['cid'], 1, $tpl);
            }
        }
        return $out;
    }
*/

?>
```

**Comment by IDragonfire** [comment]
geht jetzt alles?

**Comment by xDGeForcexD** [comment]
ja jetzt sollte alles gehen =)

**Comment by xDGeForcexD** [comment]
ich hatte lust ein bischen den ts viewer schöner zumachen so hab ich es möglich gemacht das man die channels auch ausblenden kann und eine funktion das man einstellen kann das nur channels mit usern anzeigt wird soll ich dies hier hochladen?
