### ISSUE TITLE
Man kann unregistriert Clanwarkommentare eintragen

### ISSUE THREAD

**Issue by makke81** [IDragonfire/dzcp#7]
wenn man über den direktlink
.. /clanwars/?action=details&do=add&id=1 auf das clanwarkommentarfeld 
wird das formularfeld angezeigt obwohl es nicht angezeigt werden dürfte

Lösungsansatz: 
Formular so wie beim betrachten des Clanwars selbst
 auskommentieren wenn ->chkMe == unlogged und ->reg_cwcomments == 1

so ich hoffe mal das ich das jetzt richtig gemacht habe.

**Comment by makke81** [comment]
Soweit isses gefixt aber nach dem comitten steht hier noch immer nichts drin.

**Comment by IDragonfire** [comment]
Hast es mit fix #7 commited und dann gepusht?

**Comment by makke81** [comment]
Danke das pushen hatte ich vergessen, hofffe das ich jetzt alles richtig habe^^

**Comment by IDragonfire** [comment]
Hast es auch getestet?

**Comment by makke81** [comment]
das was ich geändert hatte? klar.

mit hofffe das ich jetzt alles richtig habe^^ meinte ich eher das commiten pushen und so.

das problem besteht bestand darin das wenn man die formularverarbeitung direkt aufruft (dazu brauchte ich nichtmal das formular)  eine fehlermeldung von DZCP kommt das der capcha fehlt und man dann die möglichkeit hat alles nochmal ausfüllen zu dürfen.
das einzige was gefehlt hat ist vor der  verarbeitung abzufragen ob derjenige überhaupt berechtigt ist diese funktion zu nutzen. das habe ich somit erledigt, der gesammte code zwischen der IF ELSE ist so geblieben, hab ihn nur um einen tab eingerückt, das interpretiert das vergleichtool wohl ebenfalls als änderung?

**Comment by IDragonfire** [comment]
Sieht alles richtig aus ;) kannst mal ein pull request (github.com oben rechts) machen?

**Comment by Koma83** [comment]
Getestet und funktioniert!
