### ISSUE TITLE
Forum: sort subkat manualy

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#71]
Ermöglicht es Subkategorien manuell zu sortieren.
Man muss nicht länger Nummer davorstellen, oder auf andere Tricks zurückgreifen ...

**Comment by IDragonfire** [comment]
weiter committs dazu:

89aa8b1de587851c150e523e9e5472a0c8f9061b
a6926d5c6dcb8807686381e229504ddb7b9c590d
3f4a976d5a8ecf89bc29f53468efc0ecb9c53728

**Comment by hybernate** [comment]
erledigt, getestet und für io befunden

https://github.com/hybernate/dzcp/commit/7a6820a4481e218d6253b71d15f7ffe323b5ec62#commitcomment-1489865

kann geschlossen werden.

**Comment by IDragonfire** [comment]
Erst wenn ich es im Hauptrepo übertragen habe ... Du kannst ja mal den Pull Request machen ... Oben rechts der Button in deinem Repo ...

**Comment by IDragonfire** [comment]
muss unbedingt getestet werden, deswegen lasse ich es offen ...
Ist auf der betaSeite !!!

**Comment by xDGeForcexD** [comment]
hm schon der erste bug ...

wenn man in einem neu erstellten forum eine subkat machen möchte steht bei position noch ein andere subkat  von einem anderen forum

es bleibt nach einem erstellten subkat immer noch nur ein subkat von einem andere forum

**Comment by hybernate** [comment]
done. bitte testen

**Comment by xDGeForcexD** [comment]
ok bei mir funktionierts

**Comment by Koma83** [comment]
Wenn ich die angelegte Sub Kat angelegt habe und editieren will komme ich immer wieder auf die Hauptkategorien.

**Comment by hybernate** [comment]
es wäre ganz nett wenn du etwas detailierter wärest.... und dich etwas besser ausdrückst das ist unheimlich schwer zu verstehen.

**Comment by xDGeForcexD** [comment]
man kann keine sub kats editieren der link ist falsch deshalb kommt man immer auf die hauptseite von den forenkatogorien

**Comment by hybernate** [comment]
ah das verstehe ich schon besser ^^ aber das verwundert mich daran hatte ich nix geändert....

Wenn die beta seite ja mal funktionieren würde könnte man auch mal schauen aber der webspace ist schrott...

**Comment by hybernate** [comment]
mh bei mir lokal funktioniert das aber richtig.... irgendwas ist da wohl schief gelaufen auf der beta...

**Comment by IDragonfire** [comment]
Kann ja beim upload passiert sein, oder der installer der db ...

**Comment by hybernate** [comment]
neee is ein fehler von mir ich muss nur nachschauen
