### ISSUE TITLE
Server: Game Queries fehlen

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#8]
Server-Query für neue Spiele fehlen:

Battlefield 3
http://www.dzcp.de/forum/?action=showthread&id=14737
http://www.dzcp.de/forum/?action=showthread&id=14877

Call of Duty Black Ops
http://www.dzcp.de/forum/?action=showthread&id=14153
http://www.dzcp.de/forum/?action=showthread&id=14636

Call of Duty Modern Warfare
http://www.dzcp.de/forum/?action=showthread&id=14913

Crysis 2
http://www.dzcp.de/forum/?action=showthread&id=14414

**Comment by HellBz** [comment]
Kann noch eine Open-TTD- Query anbieten

http://www.dzcp-addons.eu/downloads/?action=download&id=67

Battlefield 3
http://www.dzcp-addons.eu/downloads/?action=download&id=68

**Comment by IDragonfire** [comment]
Irgendwer hatte auch mal eine Trackmania Query ...

http://www.dzcp.de/forum/?action=showthread&id=13120
http://www.dzcp.de/forum/?action=showthread&id=12184
http://www.dzcp-zone.de/forum/index.php?action=showthread&kid=10&id=1554

**Comment by HellBz** [comment]
Habe die Query von einem User bekommen..

http://www.mediafire.com/?n2sgn696enwqn9b

matrix142 
http://www.dzcp.de/user/?action=user&id=30560

**Comment by IDragonfire** [comment]
Sehr gut ...
Koma wollte sich darum kümmern ...
dann hat er es leichter ...

**Comment by HellBz** [comment]
Die Querys von meiner Seite können gern im CMS genutzt werden @Koma @all

**Comment by IDragonfire** [comment]
wenn wer mal Zeit hat kann wer die Namen der Queries (die im Adminmenü in der Auswahlbox der Liveabfrage angezeigt werden), oder die Funktion in der der bbcode.php verschönern
f029429b60cd35b7b8e8e19419a7a557929f12d7
(ist unschön, dass man alles manuell Eintragen muss, oder sonst der Name nicht so schick aussieht)
