### ISSUE TITLE
Validierung der HTML Files

### ISSUE THREAD

**Issue by hybernate** [IDragonfire/dzcp#80]
Das System ist nicht valide! schwerwiegende fehler.

**Comment by hybernate** [comment]
zur zeit bearbeite ich die mousover informationen. durch das html gerüst in den links sind diese nicht valide. ein valides system habe ich bereits geschrieben ich muss es nur noch benutzerfreundlicher gestalten und die funktion noch verbessern. Wenn das erledigt ist update ich alle dateien die eine hover funktion nutzen.

**Comment by hybernate** [comment]
startseite valide!!!!!!!!!!!!!!!!

**Comment by IDragonfire** [comment]
Warum nimmst du alle html5 tags raus?

**Comment by hybernate** [comment]
ich nehme die tags raus weil sie nicht valide sind.....

**Comment by hybernate** [comment]
schreib um auf html 5 wenn du den gesamten quellcode umschreiben willst... viel spass 3 wochen validierung. ganz grosser tip bleib bei XHTML 1.0. denn das gesamte system ist darauf ausgelegt und nur durch das reinschreiben von html5 tags funktionieren die nicht dann muss auch doctype geändert werden. und dann schon mal von vorneweg die meta tags geändert werden etc etc etc ich brauch da nicht weiter drauf eingehen einfach zu viel aufwand das ding auf html5 um zu schreiben.

**Comment by hybernate** [comment]
gib jedem eingabefeld das einen autofocus haben soll eine id und zwar id="autofocus" dann mach ich dir deinen autofocus. feld leer oder nicht ist schon in php drin doppelt brauchen wir das nicht. ausserdem hab ich das required in einer sekunde umgangen und kann das formular abschicken.....

**Comment by IDragonfire** [comment]
Die html5 Tags sind von acecom und gehen wunderbar, valide ist dzcp an so vielen Stellen nicht ... reuqired ist ja nur eine Warnmeldung im Browser ... php technisch wird das ja auch getestet ... doctype habe ich die Tage von html5 zurückgestellt, da wie du sagtest nur ein paar Dinge angepasst wurden ... Ich meine die tags geben nur valid warnings und keine errors

**Comment by hybernate** [comment]
hab dir die autofocus funktion verbaut, dann habt ihr wenigstens euer autofocus. lasst das mit dem html5 das ding soll valide sein und weder errors noch warnings ausspucken und ich habe es fast soweit. die ganzen show seiten sind schon 100% valide.

**Comment by hybernate** [comment]
meine meldung auf w3c validator: This document was successfully checked as XHTML 1.0 Transitional!

**Comment by IDragonfire** [comment]
wenn du fertig bist, nenne das Template am besten dann version 1.6,
fände ich passend, oder?

**Comment by hybernate** [comment]
alles klar das mache ich

**Comment by IDragonfire** [comment]
war nur ein Vorschlag, fände ich sinnvoll^^

**Comment by hybernate** [comment]
ja doch der vorschlag ist richtig. benenne ich dann um ^^ keine sache

**Comment by IDragonfire** [comment]
schaffst du es bis morgen?

**Comment by hybernate** [comment]
Validierung abgeschlossen!!!

**Comment by IDragonfire** [comment]
Was ist hiermit?

https://github.com/hybernate/dzcp/commit/06c3bfa5b47cfbc4f2cccf1f863fd61bb8514c30

btw. ich schließe es erst, wenn es im Hauptrepo ist ;)

**Comment by hybernate** [comment]
schau ich heut abend noch mal an aber das ist nicht wichtig das sind nur die bilder beim kalender... beim mouseover also clanwar, geburtstags etc.... wäre meiner meinung nach nicht wichtig diese an zu zeigen

**Comment by IDragonfire** [comment]
Im Mouseover ist es nicht so schlimm,
als würden sie in der Zelle des Tages fehlen,
da hast du Recht ;)

Solltest du es nicht schaffen, machen wir ein neues Issue auf, was dann nicht
in dzcp1.6 kommt ^^

**Comment by hybernate** [comment]
abgeschlossen

**Comment by IDragonfire** [comment]
Habe mal nach autofocus gesucht: 

```
D:\xampplite\htdocs\dzcp\git\inc\_templates_\version1.5\user\login.html (1 hits)
    Line 15:               onblur="this.className='inputField_dis';" [dis] autofocus required>
  D:\xampplite\htdocs\dzcp\git\inc\_templates_\version1.5\serverliste\add.html (1 hits)
    Line 11:     onblur="this.className='inputField_dis';"required autofocus>
  D:\xampplite\htdocs\dzcp\git\inc\_templates_\version1.5\gallery\admin.html (1 hits)
    Line 10:     onblur="this.className='inputField_dis';"required autofocus>
  D:\xampplite\htdocs\dzcp\git\inc\_templates_\version1.5\server\admin.html (1 hits)
    Line 14:     onblur="this.className='inputField_dis';"required autofocus>
  D:\xampplite\htdocs\dzcp\git\inc\_templates_\version1.5\user\admin.html (1 hits)
    Line 13:     onblur="this.className='inputField_dis';" autofocus/>
  D:\xampplite\htdocs\dzcp\git\inc\_templates_\version1.5\gallery\admin_addfile.html (1 hits)
    Line 6:     onblur="this.className='inputField_dis';" autofocus>
  D:\xampplite\htdocs\dzcp\git\inc\_templates_\version1.5\gallery\admin_edit.html (1 hits)
    Line 10:     onblur="this.className='inputField_dis';"required autofocus>
  D:\xampplite\htdocs\dzcp\git\inc\_templates_\version1.5\user\lostpwd.html (1 hits)
    Line 10:     onblur="this.className='inputField_dis';"autofocus required>
  D:\xampplite\htdocs\dzcp\git\inc\_templates_\version1.5\clankasse\paycheck.html (1 hits)
    Line 14:     onblur="this.className='inputField_dis_small';"required autofocus>.
  D:\xampplite\htdocs\dzcp\git\inc\_templates_\version1.5\user\register.html (1 hits)
    Line 11:     onblur="this.className='inputField_dis';" value="[r_name]" autofocus required/>
  D:\xampplite\htdocs\dzcp\git\inc\_templates_\version1.5\user\secure.html (1 hits)
    Line 9:            onblur="this.className='inputField_dis_small'" autofocus>
  D:\xampplite\htdocs\dzcp\git\inc\_templates_\version1.5\admin\skatform.html (1 hits)
    Line 11:     onblur="this.className='inputField_dis';"autofocus required>
  D:\xampplite\htdocs\dzcp\git\inc\_templates_\version1.5\errors\wmodus_login.html (1 hits)
    Line 10:           onfocus="this.className='inputField_en';if(this.value=='Admin') this.value='';" value="Admin" required autofocus/>
```

**Comment by IDragonfire** [comment]
müssen GANZ zum Schluss das Template umbennen in version 1.6 ...

**Comment by IDragonfire** [comment]
machen wir in der Finalen ...
