### ISSUE TITLE
URL erkennung

### ISSUE THREAD

**Issue by xDGeForcexD** [IDragonfire/dzcp#82]
Hi,
dies ist zwar kein Bug aber eine Idee.

Sollen wir vill in die BBCode funktion einbauen das er urls automtisch verlinkt?

**Comment by hybernate** [comment]
mh ist eine gute idee aber ich würde es so machen das man es auch abschalten kann wenn gewünscht denn nicht jeder mag sowas.

**Comment by hybernate** [comment]
http://www.phpbox.de/tipsundtricks/url-erkennen-verlinken.php

einfachste lösung finde ich... musst du nur in die bbcode integrieren.

**Comment by xDGeForcexD** [comment]
hat ich auch gefunden^^ ich machs gleich fertig

**Comment by IDragonfire** [comment]
Darüber müssen wir mal diskutieren,
ist schön das du es programmiert hast,
aber dass man es NUR global ein und ausschalten kann finde ich eine elegante Lösung ...
Müsste man mal mit allen Besprechen ...
Ich habe ein Milestone für dzcp 1.6. erstellt
(http://de.wikipedia.org/wiki/Meilenstein_(Projektmanagement))
Bitte sich erstmal um die Issues darin kümmern ...
Wir sollten uns auch im TS mal Treffen ...
http://www.doodle.com/pq6sqf6cey3a3fk3

**Comment by IDragonfire** [comment]
Also ich finde das nicht so toll,
global an und aus ...
Die Idee global es an- und auszuschalten würde ich drin lassen,
aber wenn man es global anschaltet sollte der User die Möglichkeit haben, dies für einen Post (eventuell für sein ganzen Profil) auszuschalten, bzw. es einschalten können (oder eventuell nicht einschalten, wenn global aus ..)

**Comment by IDragonfire** [comment]
Wir sollten im Adminmenü auch eine bessere Beschreibung wählen ..

Funktioniert nicht mit https ...

**Comment by IDragonfire** [comment]
Wie sieht es in der Shoutbox aus ?

**Comment by IDragonfire** [comment]
Wir sollten eine Beschreibung im Adminmenü hinzufügen.
Des Weiteren tendiere ich dazu Standardmässig dieses Feature anzuschalten ...

**Comment by xDGeForcexD** [comment]
jo fänd ich auch besser wenn man es standardmäsig auf an macht und wegen der beschreibung sollte man sich auch was einfallen lass

**Comment by IDragonfire** [comment]
magst noch die Beschreibung einfügen im Adminmenü?

**Comment by IDragonfire** [comment]
BUG:
http://beta.dzcp.de/forum/?action=showthread&id=1&page=1#p1

Aus (ohne URL ERkennung) 

``` html
<a href="http://www.dzcp.de">www.dzcp.de</a>
```

wird (mit Erkennung)

``` html
<a href="a target=" _blank"="" "http:="" www.dzcp.de"="" a="">www.dzcp.de</a>`
```

**Comment by xDGeForcexD** [comment]
hm leider sind meine regex Kenntnisse nicht so gut und deshalb kann ich jetzt keinen fehler finden :(

kann vill jemand mal schauen ob er eine lösung hat?

**Comment by IDragonfire** [comment]
Ich hoffe ich schaffe es heute ...

**Comment by xDGeForcexD** [comment]
bei mir funktionierst :)
