### ISSUE TITLE
Adminmenü -> User hinzufügen nicht möglich 

### ISSUE THREAD

**Issue by acecom** [IDragonfire/dzcp#84]
Bei angabe des Wohnorts kann das Formular nicht mehr mit Regestrieren abgeschicht werden Nach absenden des Formulars wird man nichtmehr aufs leer User hinzufügen Formular zurückgeleitet.

**Comment by IDragonfire** [comment]
Ich bin der Schuldige ...

https://github.com/IDragonfire/dzcp/blob/3cb5414e748d02724d7bcf4cab1ef0760529491d/inc/_templates_/version1.5/membermap/geocoder.html#L20

und

https://github.com/IDragonfire/dzcp/blob/3cb5414e748d02724d7bcf4cab1ef0760529491d/inc/_templates_/version1.5/membermap/geocoder.html#L25

müssen natürlich variable sein ...
