### ISSUE TITLE
Adminmenü ->Links    Link als Bannerlink hinzufügen nicht möglich

### ISSUE THREAD

**Issue by acecom** [IDragonfire/dzcp#85]
bei angehaken Bannerlink und abschicken des Formulars wird folgende Fehlermeldung ausgegeben "Du musst eine Linkbeschreibung angeben! "

**Comment by xDGeForcexD** [comment]
hm ist das nicht normal weil die linkbeschreibung ja neben den hits steht

aber ein weitere bug ist das das input feld für die bildaddresse nicht angezeigt wird
