### ISSUE TITLE
Adminmenü -> Seitenadmin / Allgemeine Einstellungen ->User:Profilbildgröße begrenzt die größe der Katpics 

### ISSUE THREAD

**Issue by acecom** [IDragonfire/dzcp#86]
die Einstellung der Profilbildgröße bezieht sich auch auf die Begrenzung der uploadgröße fürs die Katpics News/Artikel möglicherweiße auch noch andere Picuploads im CMS

**Comment by IDragonfire** [comment]
k, müsste man den Text anpassen ...
