### ISSUE TITLE
Adminmenü -> Partnerbuttons -> upload Eingabefeld ohne Funktion

### ISSUE THREAD

**Issue by acecom** [IDragonfire/dzcp#88]
unter uploads ist keine eingabe ins Inputfeld / Dateiupload möglich

**Comment by IDragonfire** [comment]
Bei mir geht es ..
welchen Browser benutzt du?

**Comment by acecom** [comment]
Parnerbuttons->Hinzufügen->upload  Datei: Inputfeld

IE ohne Funktion 
Chrome wird das Feld nicht angezeigt
FF öffnet sich beim klick ins Feld der Dateiuploader

denkmal ist ein schönheitsfehler 
ps. an derstelle fehlt oben auch die admin navigation

**Comment by IDragonfire** [comment]
Häh?
Bei mir geht alles ...
wir reden von:

http://beta.dzcp.de/admin/index.php?admin=partners

wenn ich was eintragen will kommt:

http://beta.dzcp.de/upload/?action=partners

ähnlich bei edtieren,
geht bei mir unter Chrome und FF

**Comment by IDragonfire** [comment]
BITTE BESCHREIBE MAL GENAU WAS DU MACHST ...
ich glaube das ist ein Problem wie wir die Dinge sehen ...

**Comment by hybernate** [comment]
ich kann keinen fehler nachvollziehen. 

getestet mit: 
ie6 - ie8
mehrere firefox versionen
mehrere safari versionen
mehrere opera versionen
arora
omniweb
und iphone3 browser

überall wird es angezeigt.....

**Comment by acecom** [comment]
es liegt an meinem rechner am laptop geht auch ->Close

**Comment by hybernate** [comment]
ich wusste es ^^
