### ISSUE TITLE
Forum: TinyMCE  Links

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#89]
Manchmal werden Links nicht richtig erkannt ...

http://www.dzcp.de/forum/?action=showthread&id=15209&page=1#p2

Konnte das jetzt gerade nicht reproduzieren,
aber ich meine, wenn ich z.B. aus Chrome einen Link kopiere und dort das
http:// nicht mitkopiere stellt dzcp automatisch die Domain mit aktuellen Pfad dran ...
Firefox kann irgendwie gar keine Links kopieren ...

Man müsste dies mal ausführlich testen ...

**Comment by xDGeForcexD** [comment]
der fehler kommt wenn du zb. [url]test.de[/url] machst oder den html code manuell eingibst dann passiert das

**Comment by IDragonfire** [comment]
hoffentlicht führt das zu keinen Seiteneffekten ...

**Comment by IDragonfire** [comment]
kommt es, 
wenn man einen internen Link postet ...

Quelle:
http://www.dzcp.de/forum/?action=showthread&id=15209&page=1#p1
