### ISSUE TITLE
User: Sonderzeichen in Loginname nicht möglich

### ISSUE THREAD

**Issue by IDragonfire** [IDragonfire/dzcp#9]
User welche im Loginnamen Sonderzeichen haben können sich nicht einloggen ...

entweder Sonderzeichen verbieten
oder 
fixen

**Comment by IDragonfire** [comment]
geht bei mir ...

**Comment by makke81** [comment]
mit sonderzeichen sind nicht die umlaute gemeint,sondern so sachen wie ! \* und so weiter
wobei die filter doch eigentlich beim registrieren und beim login verwendet werden sodas das garnicht auffallen dürfte.
oder irre ich mich da jetzt?

**Comment by IDragonfire** [comment]
hat das wer jetzt getestet?

**Comment by IDragonfire** [comment]
Ok,
Testuser:

Ηдллιвдζ

Forum:
http://www.dzcp.de/forum/?action=showthread&id=15102
Dank an EmoCore1990

**Comment by acecom** [comment]
username / passwörter mit äöü.... funktioniert nicht bei user hinzufügen übers adminmenü

**Comment by IDragonfire** [comment]
bei Registrierung geht es,
nur über Admin -> User hinzufügen nicht
up Funktion wurde vergessen zu benutzen ...
